apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-qrvf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-qrvf
    app.kubernetes.io/part-of: my-app-2
  name: devfile-sample-java-springboot-basic-qrvf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-qrvf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-qrvf
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/qe-chuo-tenant/my-app-2/devfile-sample-java-springboot-basic-qrvf@sha256:95c0f152ba6bc470323524aeffc4646bb0e6e730e7974a4b31a195712aecd5c5
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
