apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-yxx8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/qe-chuo-tenant/my-app-2/devfile-sample-python-basic-yxx8@sha256:6ee82a3a478d2798efbb7dd62de02849fa0cc9ac93bdcc0448c4913e49f279dc
        name: my-python
        resources: {}
status: {}
